image: node:13.8.0

stages:
  - prepare
  - build
  - test

cache:
  paths:
    - node_modules/

prepare:
  stage: prepare
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm run build
  dependencies:
    - prepare
  artifacts:
    paths:
      - dist

lint:
  stage: test
  script:
    - npm run lint

test-unit:
  stage: test
  script:
    - npm run test
  dependencies:
    - prepare
  artifacts:
    paths:
      - src/tests/__snapshots__